# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112K4z8K4ZC0QP52JkQCIGZCY9KdqUWRK
"""

patients = [
    ("Alice", 68, 1.65),
    ("Bob", 85, 1.75),
    ("Charlie", 95, 1.80),
    ("David", 76, 1.70)
]
def calculate_bmi(weight, height):
    return weight / (height ** 2)
patients_with_bmi = [(name, weight, height, calculate_bmi(weight, height)) for name, weight, height in patients]
sorted_patients = sorted(patients_with_bmi, key=lambda x: x[3], reverse=True)
print("Patients sorted by BMI (highest to lowest):")
for patient in sorted_patients:
    print(f"{patient[0]} - BMI: {patient[3]:.2f}")