# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s0E5k0Ul7GUps3Ie6B5wNC7Sq7BqlqPO
"""

import numpy as np
heart_rate_readings = np.array([72, 75, 68, 70, 74, 78, 69])
average_heart_rate = np.mean(heart_rate_readings)
highest_heart_rate = np.max(heart_rate_readings)
lowest_heart_rate = np.min(heart_rate_readings)
print("Average Heart Rate:", average_heart_rate)
print("Highest Heart Rate:", highest_heart_rate)
print("Lowest Heart Rate:", lowest_heart_rate)