# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBAEJxbVptd5-duy5KrHPGrBdzEIm2Oh
"""

patient_name = "Muthu Kumar "
patient_age = 35
patient_weight_kg = 75
patient_height_m = 1.75
patient_bmi = patient_weight_kg / (patient_height_m ** 2)
print(f"Patient Name: {patient_name}")
print(f"Age: {patient_age} years")
print(f"BMI: {patient_bmi:.2f}")