# -*- coding: utf-8 -*-
"""Day1_Python_for_DS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b8clMhOloCBa8hCsYGJyTfmDnhKUL_-I
"""

print("Hello, Excited to start Data Science.")



customer_name="John Doe"
customer_age=28
customer_balance=120.75
print("Customer:",customer_name)
print("Age:",customer_age)
print("Balance:",customer_balance)

product_price=200
discount=product_price*0.10
final_price=product_price-discount
print("Final Price after Discount:",final_price)

import numpy as np
sales=np.array([150,200,250,300,400,350,500])
print("Sales Data:",sales)

print("Average Sales:",np.mean(sales))
print("Highest Sales:",np.max(sales))
print("Lowest Sales:",np.min(sales))

import pandas as pd
data={
    "Customer":["Alice","Bob","Charlie"],
    "Age":[25,30,35],
    "Amount Spent:":[120,200,150]
}
df=pd.DataFrame(data)
print(df)

from google.colab import files
uploaded = files.upload()
df = pd.read_csv("customer_data.csv")
df.head()

import pandas as pd
df=pd.DataFrame({
    "Amount Spent":[200,250,300,400]
})
high_spenders=df[df["Amount Spent"]>150]
print(high_spenders)

df_sorted=df.sort_values(by="Amount Spent",ascending=False)
print(df_sorted)

df["Loyalty Points"]=df["Amount Spent"]//10
print(df)

df.to_csv("cleaned_customer_data.csv",index=False)
files.download("cleaned_customer_data.csv")

